version: '3'
services:
  postgres:
    image: 'postgres:14.1'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis: 
    image: 'redis:6.2'
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    client:
      build: 
        dockerfile: Dockerfile.dev
        context: ./client
      volumes:
        - /usr/src/app/node_modules
        - ./client:/usr/src/app
    worker:
      build:
        dockerfile: Dockerfile.dev
        context: ./worker
      volumes:
        - /usr/src/app/node_modules
        - ./worker:/usr/src/app